# Sort, Seqrch and counting Function

In [1]:
import numpy as np

In [3]:
arr = np.array([4,5,6,2,1,4,7,8,9,5,4,7,1])

In [4]:
arr

array([4, 5, 6, 2, 1, 4, 7, 8, 9, 5, 4, 7, 1])

In [5]:
np.sort(arr)

array([1, 1, 2, 4, 4, 4, 5, 5, 6, 7, 7, 8, 9])

In [11]:
np.searchsorted(arr, 7) # shows where or the index number in which the value can be putted after sorting the array.

6

In [12]:
arr1 = np.array([0,25,41,0,45,77,0,3,6,0,2,0,0,7])

In [13]:
arr1

array([ 0, 25, 41,  0, 45, 77,  0,  3,  6,  0,  2,  0,  0,  7])

In [15]:
np.count_nonzero(arr1) # shows how many non zero value is availabe 

8

In [17]:
np.where(arr > 5) # shows the index values in which the values are grater than 5

(array([ 2,  6,  7,  8, 11]),)

In [20]:
np.extract(arr > 5, arr) # extract the values of the array which are greater than 5 values having in the array

array([6, 7, 8, 9, 7])

# Numpy - Byte Swapping

In [21]:
arr

array([4, 5, 6, 2, 1, 4, 7, 8, 9, 5, 4, 7, 1])

In [22]:
arr.byteswap()

array([288230376151711744, 360287970189639680, 432345564227567616,
       144115188075855872,  72057594037927936, 288230376151711744,
       504403158265495552, 576460752303423488, 648518346341351424,
       360287970189639680, 288230376151711744, 504403158265495552,
        72057594037927936])

# Numpy - Copies and Views

In [25]:
a = np.copy(arr) # deep copy

In [26]:
a

array([4, 5, 6, 2, 1, 4, 7, 8, 9, 5, 4, 7, 1])

In [29]:
b =arr.view() # swallow copy

In [30]:
b

array([4, 5, 6, 2, 1, 4, 7, 8, 9, 5, 4, 7, 1])

In [31]:
a

array([4, 5, 6, 2, 1, 4, 7, 8, 9, 5, 4, 7, 1])

# Numpy - Matrix Library

In [32]:
import numpy.matlib as nm

In [33]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [34]:
nm.zeros((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy - Linear Algebra

In [41]:
arr1 = np.random.randint([[2,3], [4,5]])

arr2 = np.random.randint([[5,3], [2,5]])

In [42]:
arr1

array([[0, 0],
       [1, 1]])

In [43]:
arr2

array([[2, 1],
       [1, 4]])

In [44]:
np.dot(arr1,arr2)

array([[0, 0],
       [3, 5]])

In [46]:
arr1 @ arr2 # this and above both same. fist one is code and second one is symbol

array([[0, 0],
       [3, 5]])