In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
# you can use as array function

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
# you can convert an array from a list by using as any array function


In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
# matrix is by default two dimensional array

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
# it dosen't convert because matrix is a subset of an array

In [17]:
a = np.array(l)

In [18]:
c = a

In [19]:
c

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c[0] = 100

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
# it is also called swallow copy

In [25]:
# because c and a having same value means they referencing the same location.  not the values. that's why when some values are changed into c then it will also effect in the a 

In [26]:
# if the values copied then the changing values will not takes effect to another variable. for example

In [27]:
d = np.copy(a)

In [28]:
d

array([100,   2,   3,   4])

In [29]:
a

array([100,   2,   3,   4])

In [30]:
a[1] = 1000

In [31]:
a

array([ 100, 1000,    3,    4])

In [32]:
d

array([100,   2,   3,   4])

In [33]:
# it is also called deep copy

In [34]:
np.fromfunction(lambda i,j : i==j , (3,3))  # it returns data as you give function

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i,j : i*j , (3,3)) 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
# another function

In [37]:
iterable = (i *i for i in range(5))

In [38]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
# separating string based on space

In [40]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [41]:
np.fromstring('45,45', sep = ',')

array([45., 45.])

# Numpy - Data Types

In [42]:
l = [2,3,4,5,6]

In [43]:
ar = np.array(l)

In [44]:
ar

array([2, 3, 4, 5, 6])

In [45]:
# checking the dimension of the array

In [46]:
ar.ndim

1

In [47]:
ar2 = np.array([[1,2,3],[4,5,6]])

In [48]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
ar2.ndim

2

In [50]:
# checking the total number of element in the array

In [51]:
ar.size

5

In [52]:
ar2.size

6

In [53]:
# calculating the shape of the array 

# shape means how many axis and elements are there

In [54]:
ar.shape

(5,)

In [55]:
ar2.shape # 1st row then column

(2, 3)

In [56]:
ar.dtype # type

dtype('int64')

In [57]:
ar2.dtype

dtype('int64')

In [58]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [59]:
ar22 # it converts the integer values to floating point values 

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [60]:
# normally tou cannot range with some integer value. or floating point number as the jump value. 

In [61]:
# but in numpy, its possible

In [62]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [63]:
np.arange(2.3,5.6, 0.3) # jump given to 0.3

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [64]:
# converting the above range in the list 

In [65]:
list(np.arange(2.3,5.6, 0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [66]:
np.linspace(1,5,10) 

# it provides 10 equal spaces between those scales (here the scale is 1 to 5)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [67]:
np.zeros(5) # provides an array of 5 zeros

array([0., 0., 0., 0., 0.])

In [68]:
np.zeros((3,4)) # two dimentional

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.zeros((3,4,2))  # we have 4x2 and 3 such kind of array

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [70]:
# you also can make 4 dimentional array but you cannot represent this via picture or graph

In [71]:
ar4 = np.zeros((3,4,2,3))

In [72]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [73]:
ar4.ndim # it will show there are 4 dimentions available

4

In [74]:
# similarly

np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
on = np.ones((3,4,5))

In [77]:
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [78]:
on + 5 # will add 5 in all values

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [79]:
on * 5 # will multiply 5 in all values

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [80]:
np.empty((3,6)) # provides empty arrays

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [81]:
np.eye(4) #identity matrixes

# identitiy matrixes are thoose matrixes who are square martixes. determinant is 1 and diaginal will be 1 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
# create a linespace between 2 to 4 and give 20 data

In [83]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [84]:
# similarly 

np.logspace(2,5,10) # default base = 10

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [85]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [86]:
# taking random number using random function

In [87]:
np.random.randn(3,4)

array([[ 0.4670165 ,  1.0830434 ,  1.01368304, -0.12543971],
       [-0.01799839, -0.25700901, -1.10322409,  0.6168624 ],
       [-0.70098898, -0.97437319,  0.21365284, -1.4955328 ]])

In [88]:
#  storing the random data in the variable arr

arr = np.random.randn(3,4) 

# the value providing in the randn function, the mean of the values will be 0. and the standard deviation will be 1

In [89]:
arr

array([[ 0.19245828, -0.28092573, -1.26501584, -0.5792475 ],
       [ 1.06028297,  0.59307811, -0.85655047,  0.62091768],
       [ 0.62075378, -2.84914272,  0.50243037, -0.56521596]])

In [90]:
# taking the random data and making a dataframe

In [91]:
import pandas as pd

In [92]:
pd.DataFrame(arr)

0         1         2         3
0  0.192458 -0.280926 -1.265016 -0.579247
1  1.060283  0.593078 -0.856550  0.620918
2  0.620754 -2.849143  0.502430 -0.565216

In [93]:
# this function normally making data

np.random.rand(3,4)

array([[0.31740495, 0.2141974 , 0.81731557, 0.85591063],
       [0.05154292, 0.74941851, 0.42676515, 0.74566073],
       [0.10960162, 0.27142757, 0.39233742, 0.92065044]])

In [94]:
# making only integer data using random


np.random.randint(1,110, (3,4))

array([[84, 13, 66, 77],
       [17, 27, 58, 89],
       [94, 10, 39,  5]])

In [95]:
# you can use 300 rows and 400 columns as well

np.random.randint(1,110, (300,400))

array([[ 80,  11,  19, ...,   4,  88,  84],
       [ 61, 104,  92, ...,  45,  32,  56],
       [ 23,  26,  45, ...,  33,  17,  43],
       ...,
       [ 70,  99,  16, ...,  38,  74,  46],
       [ 22,  89,  47, ...,  90,  61,  79],
       [103,  56,  44, ...,  58,   6,  23]])

In [96]:
# putting in a dataframe

pd.DataFrame(np.random.randint(1,110, (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     90   17    8   95   98  103   24   56   11   11  ...  108   56    8   
1     56   22   13   48    8   93   81   69   87  102  ...   74   74  107   
2    101   88  105   25   13    2   27   18   48   65  ...   21   70   96   
3     87   46   31   10  105   47   14  103   45   85  ...   79   13  102   
4     25   12   96   98   17   35   36   67  103   74  ...   41   56   29   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   97   94   27   76   88   21   70   17   69   41  ...   94  101   29   
296   71   44   83  103   69   45    8  100   68   62  ...   64   94   92   
297   26   78   75   10   48   83   32   44   88   72  ...   47   95   82   
298   68    4   61   91   79   57   94   51   61   12  ...   50   29   65   
299   92   64  109   14   71   31   95    7   84   21  ...   91   76   71   

     393  394  395  396  397  398  399  
0     35   71   49   30   18  106   75  
1     39   92   86   18   61   64   61  
2     56   28   56   78   65   97  109  
3     57   93   93   62   35   76   87  
4     95  106   69   67   67   94   54  
..   ...  ...  ...  ...  ...  ...  ...  
295    9   37   82   69   42   89   75  
296   83   62   56    6  104   58    7  
297   24   95    9  103   81  102   76  
298    5   32   32   35   65   82   27  
299   60   52   59   21   83   42   99  

[300 rows x 400 columns]

In [97]:
# storing into a csv file


pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('300 400.csv')

In [98]:
arr = np.random.rand(3,4)

In [99]:
arr

array([[0.41077906, 0.73080727, 0.05579215, 0.38062446],
       [0.58007226, 0.06261096, 0.28457137, 0.36572091],
       [0.77220641, 0.96670906, 0.00556159, 0.54494916]])

In [100]:
# converting the above shape into different shape

In [101]:
arr1 = arr.reshape(6,2)

In [102]:
arr1

array([[0.41077906, 0.73080727],
       [0.05579215, 0.38062446],
       [0.58007226, 0.06261096],
       [0.28457137, 0.36572091],
       [0.77220641, 0.96670906],
       [0.00556159, 0.54494916]])

In [103]:
# fetching 0.43670176 number from the array

In [104]:
arr1[1][1]

0.3806244628876432

In [105]:
# extracting the 0.28175447,0.25959448, and  0.73404579 values

In [106]:
arr1[2:5, 1]

array([0.06261096, 0.36572091, 0.96670906])

In [107]:
# taking another array

In [108]:
arr3 = np.random.randint(1,100, (5,5))

In [109]:
arr3

array([[ 6, 84, 23, 18, 79],
       [60, 72, 79, 42, 47],
       [24,  4, 50, 74, 81],
       [37, 38, 34, 80, 71],
       [ 4, 96, 39, 63, 50]])

In [110]:
# extract those value which are more than 50

In [111]:
arr3>50

array([[False,  True, False, False,  True],
       [ True,  True,  True, False, False],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False,  True, False,  True, False]])

In [112]:
arr3[arr3>50]

array([84, 79, 60, 72, 79, 74, 81, 80, 71, 96, 63])

In [113]:
arr3

array([[ 6, 84, 23, 18, 79],
       [60, 72, 79, 42, 47],
       [24,  4, 50, 74, 81],
       [37, 38, 34, 80, 71],
       [ 4, 96, 39, 63, 50]])

In [114]:
arr3[2:4,[1,2]]

array([[ 4, 50],
       [38, 34]])

In [115]:
arr3[0][0] = 5000

In [116]:
arr3

array([[5000,   84,   23,   18,   79],
       [  60,   72,   79,   42,   47],
       [  24,    4,   50,   74,   81],
       [  37,   38,   34,   80,   71],
       [   4,   96,   39,   63,   50]])

In [117]:
# creatimg an array for evaluating function

In [118]:
arr1 = np.random.randint(1,3, (3,3))

In [119]:
arr1

array([[2, 2, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [120]:
arr2 = np.random.randint(1,3, (3,3))

In [121]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 2]])

In [122]:
arr1 +arr2 # creates index mapping and makes addition

array([[4, 4, 3],
       [3, 4, 4],
       [3, 2, 4]])

In [123]:
arr1 -arr2

array([[ 0,  0, -1],
       [-1,  0,  0],
       [-1,  0,  0]])

In [124]:
arr1*arr2 # it does not making matrix multiplication. it simply making index multiplication

array([[4, 4, 2],
       [2, 4, 4],
       [2, 1, 4]])

In [125]:
arr1/arr2

array([[1. , 1. , 0.5],
       [0.5, 1. , 1. ],
       [0.5, 1. , 1. ]])

In [126]:
# rule 1 of martix multiplication

# column of first matrixes and row of second martixes should be equal then you can multiply otherwise you cannot

In [127]:
# @ makes matrix multiplication

In [128]:
arr1@arr2

array([[10,  9, 10],
       [10,  8, 10],
       [ 8,  6,  8]])

In [129]:
arr1/0 # generally comes error but here comes infinity

/tmp/ipykernel_308/3913564557.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # generally comes error but here comes infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [130]:
arr1 + 100

array([[102, 102, 101],
       [101, 102, 102],
       [101, 101, 102]])

In [131]:
arr1 ** 2

array([[4, 4, 1],
       [1, 4, 4],
       [1, 1, 4]])

# Numpy- Brodcasting

In [159]:
arr = np.zeros((4,5))

In [160]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [164]:
row = np.array([1,2,3,4,5])

In [165]:
row

array([1, 2, 3, 4, 5])

In [166]:
arr + row

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [167]:
# transposing the array

# for transposing the array have to be two dimensional

In [175]:
col = np.array([[1,2,3,4]])

In [176]:
col

array([[1, 2, 3, 4]])

In [177]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [178]:
col.T + arr

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [179]:
arr5 = np.random.randint(1,4, (3,4))

In [180]:
arr5

array([[3, 3, 3, 2],
       [2, 2, 3, 3],
       [2, 2, 2, 3]])

In [181]:
np.sqrt(arr5) #square root

array([[1.73205081, 1.73205081, 1.73205081, 1.41421356],
       [1.41421356, 1.41421356, 1.73205081, 1.73205081],
       [1.41421356, 1.41421356, 1.41421356, 1.73205081]])

In [183]:
np.exp(arr5) #exponent

array([[20.08553692, 20.08553692, 20.08553692,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 , 20.08553692, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 , 20.08553692]])