# Numpy - Array Manipulation 

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10, (3,4))

In [4]:
arr

array([[2, 8, 3, 1],
       [3, 9, 3, 1],
       [4, 2, 7, 5]])

In [5]:
arr.reshape(6,2)

array([[2, 8],
       [3, 1],
       [3, 9],
       [3, 1],
       [4, 2],
       [7, 5]])

In [6]:
arr.reshape(2,6)

array([[2, 8, 3, 1, 3, 9],
       [3, 1, 4, 2, 7, 5]])

In [7]:
arr.T

array([[2, 3, 4],
       [8, 9, 2],
       [3, 3, 7],
       [1, 1, 5]])

In [9]:
arr.flatten() #creatting one dimensional data from two or more dimentional data

array([2, 8, 3, 1, 3, 9, 3, 1, 4, 2, 7, 5])

In [10]:
arr1 = np.array([1,2,3,3,4])

In [11]:
arr1

array([1, 2, 3, 3, 4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1, axis = 1) #helps to expand dimention of an array

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [15]:
np.expand_dims(arr1, axis = 0) #expand dimention across the row

array([[1, 2, 3, 3, 4]])

In [16]:
data = np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data) #helps to squeeze the data 

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 3, 4])

In [22]:
np.repeat(arr1, 3) # repeat the array 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [26]:
np.roll(arr1, 3) # rolls the numbers of the array 3 times


array([3, 3, 4, 1, 2])

In [28]:
np.diag(arr1) #it makes two dimensional array and the data will be put in the diagonal order

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Numpy - Binary Operation

In [35]:
arr2 = np.random.randint(1,10, (3,4))

In [36]:
arr3 = np.random.randint(1,10, (3,4))

In [37]:
arr2

array([[9, 5, 5, 6],
       [9, 1, 2, 6],
       [7, 7, 8, 5]])

In [38]:
arr3

array([[8, 5, 3, 4],
       [5, 9, 6, 6],
       [4, 8, 6, 7]])

In [40]:
arr2 + arr3 # perfoming index operation

array([[17, 10,  8, 10],
       [14, 10,  8, 12],
       [11, 15, 14, 12]])

In [41]:
arr2 - arr3

array([[ 1,  0,  2,  2],
       [ 4, -8, -4,  0],
       [ 3, -1,  2, -2]])

In [42]:
arr2 * arr3

array([[72, 25, 15, 24],
       [45,  9, 12, 36],
       [28, 56, 48, 35]])

In [43]:
arr2/arr3

array([[1.125     , 1.        , 1.66666667, 1.5       ],
       [1.8       , 0.11111111, 0.33333333, 1.        ],
       [1.75      , 0.875     , 1.33333333, 0.71428571]])

In [44]:
# remainder operation

arr2%arr3

array([[1, 0, 2, 2],
       [4, 1, 2, 0],
       [3, 7, 2, 5]])

In [45]:
arr2 ** arr3 

array([[43046721,     3125,      125,     1296],
       [   59049,        1,       64,    46656],
       [    2401,  5764801,   262144,    78125]])

In [46]:
arr2 & arr3

array([[8, 5, 1, 4],
       [1, 1, 2, 6],
       [4, 0, 0, 5]])

In [48]:
# negation operation

~arr2

array([[-10,  -6,  -6,  -7],
       [-10,  -2,  -3,  -7],
       [ -8,  -8,  -9,  -6]])

In [49]:
# OR operation

arr2 | arr3

array([[ 9,  5,  7,  6],
       [13,  9,  6,  6],
       [ 7, 15, 14,  7]])

In [50]:
arr2 > arr3

array([[ True, False,  True,  True],
       [ True, False, False, False],
       [ True, False,  True, False]])

# Numpy - String Function

In [52]:
 np.array(['sudh', 'kumar']) # dtype='<U5' is equivalent to a string

array(['sudh', 'kumar'], dtype='<U5')

In [53]:
arr4 =  np.array(['sudh', 'kumar'])

In [54]:
arr4

array(['sudh', 'kumar'], dtype='<U5')

In [55]:
# changing the value of the string in the array to uppercase

In [56]:
np.char.upper(arr4)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [57]:
np.char.title(arr4)

array(['Sudh', 'Kumar'], dtype='<U5')

In [58]:
np.char.capitalize(arr4)

array(['Sudh', 'Kumar'], dtype='<U5')

# Numpy - Mathematical Function

In [60]:
arr2

array([[9, 5, 5, 6],
       [9, 1, 2, 6],
       [7, 7, 8, 5]])

In [61]:
np.sin(arr2)

array([[ 0.41211849, -0.95892427, -0.95892427, -0.2794155 ],
       [ 0.41211849,  0.84147098,  0.90929743, -0.2794155 ],
       [ 0.6569866 ,  0.6569866 ,  0.98935825, -0.95892427]])

In [62]:
np.cos(arr2)

array([[-0.91113026,  0.28366219,  0.28366219,  0.96017029],
       [-0.91113026,  0.54030231, -0.41614684,  0.96017029],
       [ 0.75390225,  0.75390225, -0.14550003,  0.28366219]])

In [63]:
np.tan(arr2)

array([[-0.45231566, -3.38051501, -3.38051501, -0.29100619],
       [-0.45231566,  1.55740772, -2.18503986, -0.29100619],
       [ 0.87144798,  0.87144798, -6.79971146, -3.38051501]])

In [64]:
np.tanh(arr2)

array([[0.99999997, 0.9999092 , 0.9999092 , 0.99998771],
       [0.99999997, 0.76159416, 0.96402758, 0.99998771],
       [0.99999834, 0.99999834, 0.99999977, 0.9999092 ]])

In [65]:
np.power(arr2, 2)

array([[81, 25, 25, 36],
       [81,  1,  4, 36],
       [49, 49, 64, 25]])

In [66]:
np.mean(arr1)

2.6

In [67]:
np.median(arr2)

6.0

In [68]:
np.std(arr2)

2.3746344747958346

In [69]:
np.var(arr2)

5.638888888888889

In [70]:
np.min(arr2)

1

In [71]:
np.max(arr2)

9